# Generated by Django 3.0.5 on 2021-05-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Repuestosapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='engine_from',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='engine_to',
        ),
    ]
