# Generated by Django 3.0.5 on 2021-05-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repuestosapp', '0002_auto_20210509_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='spare_code',
            field=models.CharField(max_length=15),
        ),
    ]
