# Generated by Django 3.0.5 on 2021-05-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repuestosapp', '0003_auto_20210509_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_from',
            field=models.DateField(verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_to',
            field=models.DateField(verbose_name='To'),
        ),
    ]
