# Generated by Django 3.0.5 on 2021-05-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repuestosapp', '0004_auto_20210509_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='engine_cylinder',
            field=models.IntegerField(verbose_name="Cylinder '(ccm)'"),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_ide',
            field=models.CharField(max_length=10, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_l',
            field=models.CharField(max_length=6, verbose_name='Litre'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_pistons',
            field=models.IntegerField(verbose_name='Pistons'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_power_hp',
            field=models.IntegerField(verbose_name="Power '(hp)'"),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_power_kw',
            field=models.IntegerField(verbose_name="Power '(kW)'"),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_type',
            field=models.CharField(max_length=10, verbose_name='Type'),
        ),
    ]
