# Generated by Django 3.0.5 on 2021-05-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repuestosapp', '0005_auto_20210509_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='engine_cylinder',
            field=models.IntegerField(verbose_name='Cylinder (ccm)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_power_hp',
            field=models.IntegerField(verbose_name='Power (hp)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_power_kw',
            field=models.IntegerField(verbose_name='Power (kW)'),
        ),
    ]
