# Generated by Django 3.0.5 on 2021-05-10 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Repuestosapp', '0007_auto_20210509_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='car_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Repuestosapp.car', verbose_name='Car model'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='engine_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Repuestosapp.engine', verbose_name='Engine'),
        ),
    ]
