# Generated by Django 3.0.5 on 2021-05-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repuestosapp', '0010_auto_20210515_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(max_length=30, unique=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='spare_code',
            field=models.CharField(max_length=15, unique=True, verbose_name='Code'),
        ),
    ]
